### ISSUE TITLE
Cinaslı/sesteş kelimeler

### ISSUE THREAD

**Issue by ynskoroglu** [brolin59/trnlp#3]
İyi günler, öncelikle çalışmanız için teşekkür ederim. Şu an cümle analizinde sıkıntısız bir şekilde kullanıyorum.  Aslında belirteceğim durum çok spesifik durum ama sürekli karşıma çıktığı için bildirmek istedim.  "Pahalı" kelimesinin hecelenmesinde "paha+lı" yerine "pahal+ı" şeklinde veriyor. Biraz araştırdığım cimri manasında pahal diye bir kelime olduğunu buldum ama takdir edersiniz ki pek popüler bir kelime değil.

Belki hızlı bir çözüm olarak pahal kelimesi kaynak kütüphaneden çıkarılabilir, yada algoritma yapım eklerini çekim eklerine göre önceliğe koyabilir. Bununla beraber ileride farklı cinaslı veya sesteş örnekler benzer hatalar çıkarabileceği için paylaşmak istedim.

![image](https://user-images.githubusercontent.com/37922796/85413596-ad34b300-b573-11ea-9d6b-b527b400f99e.png)

İyi çalışmalar

**Comment by brolin59** [comment]
Öncelikle teşekkür etmek istiyorum. Aynı şey benimde dikkatimi çekmişti ve son yayınladığım versiyonda bunu düzelttim. Muhtemelen ilk yayınladığım şekli ile kullanıyorsunuz. Tekrar indirip denerseniz sevinirim. Ayrıca son yayınladığım şekli ile birkaç faydalı fonksiyon daha ekledim. Örneğin;

``` python
from trnlp import TrnlpWord

obj = TrnlpWord()

obj.setword("türkiyedeki")
print(obj. correct_form())

>> "Türkiye'deki"

obj.setword("gelcem")
print(obj. correct_form())

>> geleceğim

```

Kelime yada cümle düzeltmeleri için "SpellingCorrector" klası eklendi. Açıklamalı kullanım şekli wiki sayfasında mevcut.

İlgi ve alakanız için teşekkür ederim. Uyarı ve önerilerinizi her zaman bekliyorum.

İyi Çalışmalar.

**Comment by ynskoroglu** [comment]
Güncel versiyonda belirttiğiniz gibi düzgün ayırım yapıyor. 

Konu hakkında düşünürken sorunun aslında biraz daha komplike olduğunu fark ettim. Türkçe'deki bazı ekler birleştirilince başka eklerle aynı harflere ulaşılabiliyor. Aynı zamanda kelimlerin son 1-2 harfi de bazen bu sesteşliğe dahil olabiliyor. Özellikle -me,-a,-i,-l gibi yapım ekleriyle kafa yorunca sıkıntı yaratacak bir çok örnek çıkartabiliyor. Ancak günün sonunda bu örnekler genelde çok nadir rastlanılacak sonuçlar ve ayıklanabilir. Burada sıkıntı algoritma'nın yetersizliğinden değil Türkçe'nin bükülebilirliğinden kaynaklanıyor. Bana kalırsa algoritma yapım eklerinin kombinasyonlarını çekim eklerinin önüne koyduğu sürece yeterli seviyede. Belki ilerleyen zamanlarda uç noktalara dair bir test tasarlanabilir.

Eğer yapım eklerini topluca bakmak isterseniz [wikipedia](https://tr.wikipedia.org/wiki/Yap%C4%B1m_eki)'da gerçekten güzel bir derleme yapılmış.

Uygun görürseniz, issue'yu da kapatabilirsiniz. Kolay gelsin.
