### ISSUE TITLE
Hatalı düzeltme

### ISSUE THREAD

**Issue by hazarek** [brolin59/trnlp#4]
**Describe the bug**
Hatalı düzeltme

Readme.md dosyalarında imla hataları olduğunu farkettim düzeltmek için `correction()` fonksiyonunu kullanmak aklıma geldi.

Sıkça sorulan sorular kısmından bir cümle.
```
from trnlp import SpellingCorrector

obj = SpellingCorrector()

obj.settext("""Türkçe'nin yapısından dolayı bir kelime için, ek almış yada almamış olsun, birden fazla çözümleme yapılabilmektedir. Örneğin "kanat" kelimesini değerlendirirsek""")
output = obj.correction(all=True)
for x in range(len(output)):
	print(output[x][0], end=' ')
```
Çıktı;
**türkçe'nin** yapısından dolayı bir kelime için ek almış **yada** almamış olsun birden fazla çözümleme yapılabilmektedir örneğin kanat kelimesini değerlendirirsek

doğrusu;
türkçe'nin > türkçenin
yada > ya da

**Comment by brolin59** [comment]
Bilgilendirmeniz için teşekkür ederim. İşlerimin yoğunluğu sebebiyle yazılımla pek ilgilenemiyorum. İlk boş vaktimde bahsettiğiniz konu üzerinde çalışacağım inşallah.
