### ISSUE TITLE
Deasciifier hakkında

### ISSUE THREAD

**Issue by hazarek** [brolin59/trnlp#6]
https://github.com/aysnrgenc/TurkishDeasciifier

Bu deasciifier neural network ile çalışıyor. büyük verilerle eğitilirse hatasız düzeltme yapabilir. projenize dahil edersiniz diye tavsiye. iyi çalışmalar.

**Comment by brolin59** [comment]
Tavsiyeniz için teşekkür ederim. Verdiğiniz linkteki çalışmayı inceleyeceğim.
