### ISSUE TITLE
Memory Hatası ve Test Sonuçları

### ISSUE THREAD

**Issue by takicak** [brolin59/trnlp#7]
Merhaba

NLP ve Python konusunda yeniyim. 
Kütüphanenizi biraz test ettim ve çok başarılı buldum.

Benim karşılaştığım problemlerin ana kaynağı, iki kelime arasında boşluk bırakmamak olduğunu söyleyebilirim.
Önerilen kelime listesini incelemedim, ilk önerilen kelimeyi kullandım.
Test sonuçlarını aşağıda iletiyorum. Düzeltmeleri nasıl yapabileceğim konusunda yardımcı olabilir misiniz?

Kütüphanenin yapısı hakkında fazla bilgim yok, algoritmalar konusunda bir döküman var mı?
Nereye kadar düzeltme yapabiliriz, her hangi bir sınırımız var mı merak ediyorum açıkcası.

Test sırasında sürekli **memory** hatası aldığım için daha fazla çıktı elde edemedim. ( 3 farklı makinede denedim )
SpellingCorrector nesnesini yarattıktan sonra, database kayıt okuma döngüsü içinde 
tuple (row) içindeki (row[0]) stringini settext() metoduna veriyorum ve correction(all=True) şeklinde çağrımı yapıyorum.
Aşağıdaki şekilde dönen değerler içindeki ilk kelimeleri birleştirerek yeni düzeltilmiş cümlemi oluşturuyorum ve bunu database e kayıt ediyorum.

```
connection = None
try:
    connection = cx_Oracle.connect(username, password, dsn, encoding=encod)
    cursor1 = connection.cursor()
    cursor2 = connection.cursor()
    sql1 = 'SELECT F.PK, F.COMPLAINT FROM TABLE_FIX F WHERE F.COMPLAINT_FIX IS NULL ORDER BY LENGTH(F.COMPLAINT) DESC'
    cursor1.execute(sql1)
    
    obj = SpellingCorrector()
    
    for row in cursor1:
        
        hdrid = row[0]
        complaint =  row[1]
        
        if type(complaint) is not str:
            continue

        obj.settext(complaint) 
  
        kelimesecenekleri = None
        kelimesecenekleri =  obj.correction(all=True)
        
        tr_result_cumle = ''
        
        for kelime in kelimesecenekleri:
            tr_result_cumle += kelime[0] + ' '
            print("Loop...", kelime[0])
            
        sql2 = 'UPDATE TABLE_FIX F SET F.COMPLAINT_FIX = :1 WHERE F.PK = :2'
        cursor2.execute(sql2, (tr_result_cumle, hdrid))
        cursor2.execute('commit')
```

Settext metoduna verdiğim string boyu ortalama 600 karakter ama 3000 karakteri yada 100 karakteri bulduğu oluyor.
Bellek kullanımında mı hata yapıyorum, string çok mu büyük bilemedim. del obj ve gc.collect de kullandım ama çözüm olmadı.
Dediğim gibi sadece SpellingCorrector nesnesini döngüye girmeden önce bir kez yaratıyorum.
Metindeki cümleleri teker teker yada kelime kelime göndersem faydası olur mu bilemedim.
Bu konuda da önerilerinizi iletirseniz sevinirim.

Teşekkürler

43.000 karakter yani 6.000 kelime için, 580 civarında düzeltme içinde 40 adet hata, (ki hata olduğu tartışılır) en az %96 başarısınız anlamına gelir.
Düzeltilmiş metini, google yazım denetimi ile incelediğimde 70e yakın hala hatalı olabilecek kelime olduğunu gördüm. (ekte gönderiyorum)
Bu da tüm kelimeler içinde %1 gözden kaçan düzeltme demek.

Correction sonrası bulduğum hatalar
-----------------------------------------------------------
problemide problemine #aslında de eki ayrı yazılmak istenmiş.
saftada haftada #safhada yazılacağına saftada yazılmış, düzeltmesi ilk harf değişimi ile haftada olarak düzeltmiş. aslında haklı bir düzeltme, rast geldim sadece.
yönetim Yönet'im #yönetim kelimesi sözlükte yoksa belki özel isim olarak algılamış olabilir.
ahlakı5görevinizden #correction yapılmadı
bebegimikaçırdım #correction yapılmadı
merkezi merkezî #gereksiz yere i harfi uzatılmış.
bukadar çukadar #bu kadar bitişik yazıldığı için düzeltme uygulanmış, çukadar ne demek bilemedim :)
müşteri Müşteri #gereksiz yere m harfi büyük yazılmış.
iadecettim #correction yapılmadı, iade ettim yazılmak istenmiş.
dendiki dendiği #ki eki ayrı yazılmadığı için böyle bir sonuca ulaşılmış
nedirve #correction yapılmadı, nedir ve yazılmak istenilmiş.
varsistemden #correction yapılmadı, var sistemden yazılmak istenilmiş.
yazan Yazan #gereksiz yere m harfi büyük yazılmış.
bişey birey #bir şey yazılmak istenmiş, birey olarak düzeltilmiş.
herşeyi herzeyi #her şeyi ayrı yazılmak istenilmiş
bişeye bireye #birşeye yazılmak istenmiş, bireye olarak düzeltilmiş. ş ve r harfleri klavyede birbirlerine uzak olduğu için bişey kelimesini bir şey olarak düzeltilmesini önerebilirim.
rızamla mı rızamla mi #soru ekini mi olarak düzeltmiş.
getirdininiz getirdiğiniz #bendeki örnekte getirdiniz denmek istenmiş fakat düzeltme haklı sebeplerle yapılmış.
tarihi tarihî #gereksiz yere i harfi uzatılmış. muhtemel bu tarz düzeltmeler için kelimenin çümle içindeki yerini göz önünde bulundurmak gerekir.
alibeyköy #correction yapılmadı, özel isimlere eklenebilir.
aramaz iseniz aramaz İsen'iz #konuşma dili yazıya dökülmüş
oluşum Oluş'um
konuşmayı mı konuşmayı mi #soru ekini mi olarak düzeltmiş.
bellısız bellisiz #belirsiz yazılmak istenilmiş.
artık Artık #muhtemel bu tarz düzeltmeler için kelimenin çümle içindeki yerini göz önünde bulundurmak gerekir. Bendeki örnekte soru cümlesinin sonundaydı.
anlayab,ildiniz anlayan ildiniz 
samandıraya şamandıraya #Samandıra'ya yazılmak istenilmiş. Samandıra özel isimlerde yok sanırım.
seferinin seferînin #gereksiz yere i harfi uzatılmış.
tarihinde tarihînde #gereksiz yere i harfi uzatılmış.
nazilli'den nazilliden #özel isimlere eklenebilir.
üniversitesi'nden üniversitesinden #doğru mu yanlış mı bilemedim
ingilizce İngiliz'ce #doğru mu yanlış mı bilemedim
okuyan Okuyan
mutlu Mutlu
adlı Adlı
edırne edirne #özel isimlere eklenebilir.
no nom
dönüş Dönüş
luleburgaz lüleburgaz #düzeltmesi doğru yapılmış, sanırım özel isimler listesinde yok
dahili dâhilî #dahili numara anlamında kullanılmış
gıdn gıda #gidin demek istenmiş
pc ipucu #bilgisayar anlamında pc kelimesi kullanılmış.
anlayabildiniz miilk anlayan ildiniz mi #mi ilk bitişik yazılmış.
iskeçe iskele #İskeçe özel isimlere eklenebilir.

Bunlar da en başarılı düzeltmeler.
--------------------------------------------------
msjma mesajıma
göremediğniizi göremediğinizi
yapacaz yapacağız
oomasından olmasından
yokilla yok illa
gb gibi

Düzeltilmiş metin için Google un bulduğu hatalar
--------------------------------------------------
ettiteyid # etti teyid 
çukadar # bukadar bitişik kelimesini çukadar şekline getirmişti.
firme # firma
alınbaska # alın başka
dedikki # dedi ki
aşdıgım # aldığım ilk seçenek olmasa da seçeklerde üst sıralarda olmalı
dogruyol # özel isim yada ayrı yazılmalı
geçmediginiben # geçmediğini ben
defalarcaçözüm # defalarca cözüm
aradgmda # aradığımda
gördükki # gördük ki
yaşanmışçözüm # yaşanmış çözüm
bebegimede # bebeğime de
açacagımayrıca # açacağım ayrıca
söyledilerbelirttim # söylediler belirttim
dendiözellikle # dendi denildi özellikle
nedirve # nedir ve
varsistemden # var sistemden
bakıldıbirkaç # bakıldı birkaç
durulduve # duruldu ve
dedibizde # dedi biz de
aldıken # alırken
eminmisiniz # emin misiniz
işlkez # ilk kez
bulunam # bulunmam
oturturan # oturtan yada otutturan
rel # ret
hemde # hem de
yukarda # yukarıda
Yazık'tır # yazıktır
çıkmıyor sunuz ki # çıkmıyorsunuz ki
sizede # size de her zaman ayrı mı bilemedim
uyarıylamı # uyarıyla mı
bizede # bize de her zaman ayrı mı bilemedim
onada # ona da her zaman ayrı mı bilemedim
tabiki # tabi ki
herşey # her şey
heryerden # her yerden
sevise # servise yada sevişe  
yayınlıyacam  # yayınlayacağım
yazane yezanesinde # yazıhane yazıhanesinde
diyemi # diye mi
herseye # her şeye
yollıyacam # yollayacağım
birsürü # bir sürü
vrecı # verici
acıklama # açıklama
böylrmı # böyle mi
cokmu # çok mu
onmelı # önemli
ototbus # otobüs
istanbıla # İstanbul'a
körmüsünüz # kör müsünüz
sacede # sadece
söylemeyinbakın # söylemeyin bakın
galibasiz # galiba siz
istiyorumşimdi # istiyorum şimdi
dahaama # daha ama
dileyebilirsinizoncelikle # diyebilirsiniz öncelikle
kucukyalidan # küçükyalıdan
buyukcekmeceden # Büyükçekmece'den yada büyük çekmeceden
birbuçuk # bir buçuk
sağolsunlar # sağ olsunlar
bidaha # bir daha
pamdemi # pandemi
yetisememistirler # yetişememiştirler
izyein # izleyin 
kameramaniyim # kameramanıyım
melâne # sözlükte yoktur sanırım
sistemede # sistemde yada sisteme de
yüzaçık # yüzü açık
şikayetcı # şikayetçi

**Comment by brolin59** [comment]
Proje hala "alpha" aşamasında. Stabil bir versiyon için biraz fazla vakte ihtiyacım var.  Uzun zamandır proje ile ilgilenemediğimden Beta aşamasına bile geçiremedim. Bu yüzden çok geç dönüş yapıyorum kusura bakmayın. Aslında memory kullanımının gereğinden fazla olduğunun farkındayım. Bunun en büyük sebebi correction(all=True) şeklinde parametresiz giriş yapmış olmanız. Bu durumda mevcut her düzeltme fonksiyonu çalıştığından her bir kelime için yüz binlerce alternatif üretilebilir. Bu sebeple geçici bir çözüm olarak correction(all=True) şeklinde giriş yapmaktansa wiki sayfasındaki parametrelerin sadece gerekli olanlarını kullanmanız bir çözüm olabilir. Wiki sayfasında konu ile ilgili kısmın linkini aşağıda veriyorum. İnşallah faydalı olur. Geri dönüşünüz için teşekkür ederim. Vakit bulduğumda proje üzerinde çalışmaya devam edeceğim.

https://github.com/brolin59/trnlp/wiki/5.-Kelime-Kontrol%C3%BC

**Comment by takicak** [comment]
Bellek problemini size yazdım ama ben kendim sadece bitişik yazılmış sözcükleri bile ayırırken bellek hatası yaşadım.
Dediğiniz gibi bu kadar düzeltmede gayet normal.

Doğruluk payı yüksek bir veriye github hesabımdan ulaşabilirsiniz. https://github.com/takicak/turkish_nlp_source
Bilkent üniversitesi türkçe kompozisyonları. bir kaç hatalı içerik ve karakter var sanırım ama bayağı düzgün metinler içerdiğini söyleyebilirim.

Fakat ben bu source lar içindeki sözlüğü oluştururken fark ettim ki, özellikle düzeltme işlemlerinde dediğiniz gibi eğitilmiş bir veriyi kullanmak gerekiyor. Hatta amacınızla aynı konuda olan bir metin ile eğitmek gerekiyormuş. Ben çok iyi bir sözlük ile düzeltmeleri aşabileceğimi sanmıştım, olmuyormuş :)

Sizin sözlükleriniz pickle dışında başka dosyalardan da veri alsaydı eminim daha fazla kişi kullanabilirdi.
Şahsen ben pickle sözlüklere henüz kayıt eklemedim.

Gerçekten kaliteli bir kütüphane yazmışsınız, tebrikler, iyi çalışmalar.

**Comment by brolin59** [comment]
freq:dict

"freq" parametresi sayesinde kullanıcı tanımlı frekans sözlüğü kullanılabilir. Frekans sözlüğünün nasıl oluşturulabileceğine dair fikirler için Wiki sayfasından Frekans Sözlüğü Oluşturma bölümünü inceleyebilirsiniz. "freq" parametresinin sayılmış kelimeler sözlüğüne eşitlenmesi gerekmektedir.
